"""migrations

Revision ID: 7ca20ec579c6
Revises: e466e9b186cb
Create Date: 2024-05-30 16:27:51.563306

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7ca20ec579c6'
down_revision: Union[str, None] = 'e466e9b186cb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('_profilePic', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('users', '_profilePic')
    # ### end Alembic commands ###
