"""migrations

Revision ID: 8d5924953e60
Revises: 9a87d7665adb
Create Date: 2024-05-30 14:13:14.143903

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision: str = '8d5924953e60'
down_revision: Union[str, None] = '9a87d7665adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('firstname', sa.String(length=60), nullable=False))
    op.add_column('users', sa.Column('lastname', sa.String(length=60), nullable=False))
    op.drop_column('users', 'first_name')
    op.drop_column('users', 'last_name')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('last_name', mysql.VARCHAR(length=60), nullable=False))
    op.add_column('users', sa.Column('first_name', mysql.VARCHAR(length=60), nullable=False))
    op.drop_column('users', 'lastname')
    op.drop_column('users', 'firstname')
    # ### end Alembic commands ###
